const buildTxt2ImgOptions = ({prompt,negative_prompt,sampler_name,cfg_scale}) => {
    return {
        "prompt": prompt,
        "negative_prompt": negative_prompt,
        "styles": [],
        "seed": -1,
        "subseed": -1,
        "subseed_strength": 0,
        "seed_resize_from_h": -1,
        "seed_resize_from_w": -1,
        "sampler_name": sampler_name,
        "batch_size": 1,
        "n_iter": 1,
        "steps": 30,
        "cfg_scale": cfg_scale,
        "width": 512,
        "height": 512,
        "restore_faces": true,
        "tiling": false,
        "do_not_save_samples": false,
        "do_not_save_grid": false,
        "eta": 0,
        "s_min_uncond": 0,
        "s_churn": 0,
        "s_tmax": 0,
        "s_tmin": 0,
        "s_noise": 0,
        "override_settings": {},
        "override_settings_restore_afterwards": true,
        "refiner_checkpoint": "",
        "refiner_switch_at": 0,
        "disable_extra_networks": false,
        "comments": {},
        "enable_hr": false,
        "firstphase_width": 0,
        "firstphase_height": 0,
        "hr_scale": 2,
        "hr_upscaler": "Latent",
        "hr_second_pass_steps": 0,
        "hr_resize_x": 0,
        "hr_resize_y": 0,
        "hr_checkpoint_name": "",
        "hr_sampler_name": "DPM++ 2M Karras",
        "hr_prompt": "",
        "hr_negative_prompt": "",
        "sampler_index": "DPM++ 2M Karras",
        "script_name": "",
        "script_args": [],
        "send_images": true,
        "save_images": false,
        "alwayson_scripts": {}

    }
}

module.exports = buildTxt2ImgOptions;