
const buildImg2ImgOptions = ({prompt,negative_prompt,cfg_scale,denoising_strength,sampler_name,img}) => {
    return {
        "prompt": `${prompt}`,
        "negative_prompt": `${negative_prompt}`,
        "styles": [
          ""
        ],
        "seed": -1,
        "subseed": -1,
        "subseed_strength": 0,
        "seed_resize_from_h": -1,
        "seed_resize_from_w": -1,
        "sampler_name": `${sampler_name}`,
        "batch_size": 1,
        "n_iter": 1,
        "steps": 50,
        "cfg_scale": cfg_scale,
        "width": 512,
        "height": 512,
        "restore_faces": true,
        "tiling": false,
        "do_not_save_samples": false,
        "do_not_save_grid": false,
        "eta": 0,
        "denoising_strength": denoising_strength,
        "s_min_uncond": 0,
        "s_churn": 0,
        "s_tmax": 0,
        "s_tmin": 0,
        "s_noise": 0,
        "override_settings": {},
        "override_settings_restore_afterwards": true,
        "disable_extra_networks": false,
        "comments": {},
        "init_images": [
          `${img}`
        ],
        "resize_mode": 1,
        "image_cfg_scale": 0,
        "latent_mask": "",
        "sampler_index": "Euler",
        "include_init_images": false,
        "script_name": "",
        "script_args": [],
        "send_images": true,
        "save_images": false,
        "alwayson_scripts": {}
      }
}
// {
//     "prompt": "<lora:animelora:0.1>,anime style, ghibli,art, painting, anime",
//     "negative_prompt": "nsfw",
//     "styles": [
//       ""
//     ],
//     "seed": -1,
//     "subseed": -1,
//     "subseed_strength": 0,
//     "seed_resize_from_h": -1,
//     "seed_resize_from_w": -1,
//     "sampler_name": "Euler",
//     "batch_size": 1,
//     "n_iter": 1,
//     "steps": 20,
//     "cfg_scale": 7,
//     "width": 512,
//     "height": 512,
//     "restore_faces": true,
//     "tiling": false,
//     "do_not_save_samples": false,
//     "do_not_save_grid": false,
//     "eta": 0,
//     "denoising_strength": 0.5,
//     "s_min_uncond": 0,
//     "s_churn": 0,
//     "s_tmax": 0,
//     "s_tmin": 0,
//     "s_noise": 0,
//     "override_settings": {},
//     "override_settings_restore_afterwards": true,
//     "refiner_checkpoint": "",
//     "refiner_switch_at": 0,
//     "disable_extra_networks": false,
//     "comments": {},
//     "init_images": [
//       ""
//     ],
//     "resize_mode": 0,
//     "image_cfg_scale": 0,
//     "mask_blur_x": 4,
//     "mask_blur_y": 4,
//     "mask_blur": 0,
//     "inpainting_fill": 0,
//     "inpaint_full_res": true,
//     "inpaint_full_res_padding": 0,
//     "inpainting_mask_invert": 0,
//     "initial_noise_multiplier": 0,
//     "latent_mask": "",
//     "sampler_index": "Euler",
//     "include_init_images": false,
//     "script_name": "",
//     "script_args": [],
//     "send_images": true,
//     "save_images": false,
//     "alwayson_scripts": {}
//   }

module.exports = buildImg2ImgOptions;